### ISSUE TITLE
Add learning resources to README file

### ISSUE THREAD

**Issue by saurabhnative** [codeclassifiers/react30_13_video_player#2]
Add learning resources in README.md file related to playing video urls in react.js using API response.
Any links to youtube tutorials, official docs or articles from Medium, Dev.to or Hashnode are preferred.

**Comment by oshyam** [comment]
I Would like to Contribute.
-Adding learning resources to README.md with the mentioned link.
Thank You

**Comment by saurabhnative** [comment]
@oshyam You have been added as an assignee. Feel free to submit pull request to this repository.

**Comment by oshyam** [comment]
@codeclassifiers please add hacktoberfest-accepted as a label.
Thank You

**Comment by bvsslgayathri-8679** [comment]
I would like to contribute. Please add hacktoberfesr accepted as label

**Comment by Mamoanwar97** [comment]
I would like to contribute, can you assign it to me too?

**Comment by saurabhnative** [comment]
@bvsslgayathri-8679 and @mamoanwar97  You have been added as assignees. Feel free to submit pull request to this repository.

**Comment by saurabhnative** [comment]
@oshyam Your pull request is merged into main repo with relevant Hacktoberfest labels. Thank you for your contribution.

**Comment by praniidabomb** [comment]
@codeclassifiers Iwould like to contribute
